version: '3'

services: 
    
    database:
        image: 'mongo'
        container_name: 'mongo-container'
        environment:
            - MONGO_INITDB_DATABASE=stat-database
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes: 
            - ./mongo-volume:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports: 
            - '27017-27019:27017-27019'
