version: '3'

services: 
    
    database:
        image: 'mongo'
        container_name: 'mongo-container'
        environment:
            - MONGO_INITDB_DATABASE=stat-database
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes: 
            - ./mongo-volume:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports: 
            - '27017-27019:27017-27019'

    server:
        build:
            context: server
            dockerfile: Dockerfile
        container_name: 'server-container'
        ports:
            - '8000:8000'

    updater:
        build:
            context: updater
            dockerfile: Dockerfile
        container_name: 'updater-container'
